# Generated by Django 5.1.4 on 2025-01-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_enrollment_memebershipplan_trainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatct',
            new_name='Contact',
        ),
    ]
