# Generated by Django 5.1.4 on 2025-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=150)),
                ('price', models.IntegerField(max_length=55)),
            ],
        ),
    ]
