# Generated by Django 5.1.4 on 2025-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Login',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Logout',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='SelectWorkout',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Selectdate',
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
