# Generated by Django 5.1.4 on 2025-01-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_remove_attendance_login_remove_attendance_logout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=10)),
                ('LoginTime', models.DateTimeField(auto_now_add=True)),
                ('LogoutTime', models.DateTimeField(auto_now_add=True)),
                ('TrainedBy', models.CharField(max_length=150)),
                ('Status', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
