# Generated by Django 5.1.4 on 2025-01-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_custattendance_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custattendance',
            name='LoginTime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='custattendance',
            name='LogoutTime',
            field=models.CharField(max_length=200),
        ),
    ]
