# Generated by Django 5.1.4 on 2025-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_custattendance_date_custattendance_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custattendance',
            name='Date',
            field=models.CharField(max_length=150),
        ),
    ]
