# Generated by Django 5.1.4 on 2025-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_custattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custattendance',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
