# Generated by Django 5.1.4 on 2025-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_facility_gymcontact_gymimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_des', models.TextField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
