# Generated by Django 5.1.4 on 2025-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_gymaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='img_service/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
